theme: jekyll-theme-modernist
title: Wenjia Liu
description: "Hi, I am a Computer Science and Economics student at McGill University. I'm I'm actively looking for DA/BA intern positions starting in Summer 2022."
