theme: jekyll-theme-modernist
title: Wenjia Liu
description: "I am a junior at McGill University majoring in Computer Science, and minoring in Statistics and Economics. I'm actively looking for DA/BA intern positions starting in Summer 2022."
